### ISSUE TITLE
Locking information + balances

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/iq-bridge-ui#13]
**Is your feature request related to a problem? Please describe.**
We need to improve the lock page with information so users can understand the benefits of locking and also see current trends of other users locking IQ

**Describe the solution you'd like**
- Add a text in the top of the card similar to:

"The longer you lock your IQ, the more hiIQ you will receive. You can also get additional hiIQ by locking more IQ or extending the lock period. hiIQ decays slowly over your locking period, eventually reaching 1-to-1 with IQ."

- Create a card similar to the one in the bottom of this example (feel free to take code as reference from https://github.com/EveripediaNetwork/mindswap-ui ) 

That card should show when user fill IQ balance or when user already have balance in hiIQ:
it should show data like:
 - hiIQ balance 
 - Time locked

![image](https://user-images.githubusercontent.com/1288106/118986369-96fbc680-b97f-11eb-82e0-2e385d8dd894.png)

**Comment by kesar** [comment]
@kesar find & share formula for hiIQ

**Comment by JustinCast** [comment]
@kesar lemme know when you find the formula for hiIQ

**Comment by kesar** [comment]
i think its linear and it gives a 300% boost w a lock of 4 years 

https://github.com/EveripediaNetwork/iq-ethereum/blob/main/src/Lock/HIIQ.vy#L95

so probably its something like ( tokensLocked * 3 * numberOfDays / 1460 ) (but we need to actually test it once we can lock and get balances onchain 👍🏻

**Comment by JustinCast** [comment]
@kesar is there a way to be notified when the lock transaction / increase amount - is confirmed?. Since we need to update the hiIQ balance in the Ui, I'm thinking about a proper way to update it

**Comment by kesar** [comment]
You can check for inspiration what uniswap/quickswap does https://quickswap.exchange/#/swap it generates a place where you can see pending txs.

From the technical point of view, you will get a txID when you execute a call, so then I think you could poll that txID until its minted. ( https://docs.ethers.io/v5/api/providers/provider/#Provider-getTransactionReceipt )

You could also listen for events ( https://docs.ethers.io/v5/concepts/events/ )
