### ISSUE TITLE
new hiiq on lock shows (possible) wrong amount

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/iq-bridge-ui#135]
there could be an issue with extending lock time / amount and the new HiIQ value. Perhaps its because of the decay, or how the calculation is done. it shows more than you get.

<img width="460" alt="Captura de pantalla 2021-09-20 a las 14 58 48" src="https://user-images.githubusercontent.com/1288106/134006229-e469a903-cbee-4562-b8e0-b81f0b0db5fd.png">

**Comment by JustinCast** [comment]
@kesar how can we calculate the decay on the frontend?. Seeing the `increase_unlock_time` method on the `HIIQ.vy` contract, it is calling `_deposit_for` method, and that method is in turn, calling the `_checkpoint` one

**Comment by kesar** [comment]
i think im going to close it.. ive been checking the code and it looks calculation is fine 👍🏻 . perhaps the user was having weird behaviour because of the other issue (increasing time when its not possible). that could lead to some weird numbers.
