### ISSUE TITLE
Maintain constant colors with the donut chart

### ISSUE THREAD

**Issue by JustinCast** [EveripediaNetwork/iq-bridge-ui#138]

**Comment by JustinCast** [comment]
I was thinking about to set the colors for the donut in the local storage, but that will also lead to different colors set in the local storage for each user. Another option could be to save the colors for the top 10 stakers in a easy-to-read db. What are your thoughts on this? @0xJM @kesar

**Comment by 0xJM** [comment]
I think we can consider storing the colors in an array and then having the chart populate the colors from that

**Comment by JustinCast** [comment]
@0xJM haha that's true man. I don't know what I was thinking to get overcomplicated
