### ISSUE TITLE
Voting feature

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/iq-bridge-ui#40]
**Is your feature request related to a problem? Please describe.**
A way for voting inside of our UI

**Describe the solution you'd like**
It should be a new page with a select, that will contain the latests proposals. Defaulting to the last one active.

It should show title & description converting markdown to html in a safe way

Results should be shown initially in a pie chart (in the next iteration we will try to add an SVG w a brain :)) )

Users should have buttons to vote to different values of the proposal. Once they sign and broadcast the votes, ideally it should refresh the pie chart w new values.

User should be able to see his vote, and change if there is still time for that.

If possible, we should show the user voting power.

Extra: show list of voting similar to the snapshot page

**Useful links**

https://github.com/DimensionDev/Maskbook/blob/master/packages/maskbook/src/plugins/Snapshot/apis/index.ts
^-
```js
export async function vote(identifier: ProposalIdentifier, choice: number, address: string) {
    const msg = JSON.stringify({
        version: '0.1.3',
        timestamp: (Date.now() / 1e3).toFixed(),
        space: identifier.space,
        type: 'vote',
        payload: {
            proposal: identifier.id,
            choice,
            metadata: {},
        },
    })

    const sig = await Services.Ethereum.sign(msg, address)

    const response = await fetch(https://hub.snapshot.page/api/message, {
        method: 'POST',
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ msg, sig, address }),
    })

    const result: VoteSuccess = await response.json()
    return result
}
```

You can check our documentation here for our API if you want to integrate it on your UI: https://docs.snapshot.org/graphql-api
For signing vote and proposal you will need to use Snapshot.js client. It's not documented but i can point you to some code example from Snapshot UI
This is how we send a vote or a proposal: 
https://github.com/snapshot-labs/snapshot/blob/032f91c67ba7ebde4eb45d5585f5ff9ed26f6cac/src/store/modules/app.ts#L58-L64
This is how the client is initialized:
https://github.com/snapshot-labs/snapshot/blob/032f91c67ba7ebde4eb45d5585f5ff9ed26f6cac/src/helpers/client.ts
This is how a vote is triggered: https://github.com/snapshot-labs/snapshot/blob/975b84dabb79b001a9395572818b689f455d40ef/src/components/Modal/Confirm.vue#L103-L111

 
You can use https://demo.snapshot.org/ for that
You can setup your space like on the main snapshot website, and do test proposals and vote
The content will be not shared between demo and the main site

**Comment by kesar** [comment]
@JustinCast this is an epic task, we can have a quick call to discuss about it 👍🏻

**Comment by JustinCast** [comment]
@kesar let's have the call
