### ISSUE TITLE
Get a ENS for this project

### ISSUE THREAD

**Issue by JustinCast** [EveripediaNetwork/iq-bridge-ui#60]
@kesar do we need an ENS for our project?
- https://docs.snapshot.org/spaces/create
- ![image](https://user-images.githubusercontent.com/17890146/121264956-3d4b3580-c875-11eb-9ee9-1dd9d0adb1e5.png)
- https://app.ens.domains/
- https://docs.ens.domains/dns-registrar-guide

**Comment by kesar** [comment]
we have everipediaiq.eth

https://snapshot.org/#/everipediaiq.eth/
