### ISSUE TITLE
CZ & KO translations

### ISSUE THREAD

**Issue by JustinCast** [EveripediaNetwork/iq-bridge-ui#74]

**Comment by kesar** [comment]
can u paste in the issue the strings? I can send this directly to the translators! thanks!

**Comment by JustinCast** [comment]
@kesar 
- voting: "Voting"
- close_details: "Close details"
- open_details: "Open details"
- started: "Started"
- at: "At"
- ending: "Ending"
- ended: "Ended"
- select_for_voting: "Select for voting"
- selected: "Selected"
- see_on_snapshot: "Go to proposals",
- details: "Details"
- votes_breakdown: "Votes Breakdown"
- from: "from"
- tx_executed: "Tx executed"
- voting: "voting"
- select_a_proposal: "Select a proposal"
- select_proposal_to_see_details: "Select a proposal to see details"
- vote: "Vote"
- voting_ended: "Voting ended"
- no_votes_so_far: "No votes so far"
- swap_to_iq_erc20: "Swap to IQ ERC20"
- swap_iq_to_eos: "Swap IQ to EOS"
- transactions_broadcasted: "Transactions broadcasted"

**Comment by kesar** [comment]
korean:

voting: "투표",
close_details: "세부 정보 닫기",
open_details: "세부 정보 열기",
started: "투표 시작 날짜",
at: "시간",
ending: "투표 마감 날짜",
ended: "투표 마감",
select_for_voting: "투표를 위해 선택",
selected: "선택 완료",
see_on_snapshot: "제안 보기",
details: "세부 정보",
votes_breakdown: "투표 내역",
from: "from",
tx_executed: "트랜잭션 실행",
voting: "투표중",
select_a_proposal: "제안 선택",
select_proposal_to_see_details: "세부 정보를 보려면 제안을 선택하세요.",
vote: "투표",
voting_ended: "투표 종료",
no_votes_so_far: "지금까지 투표가 없습니다.",
swap_to_iq_erc20: "IQ ERC20으로 스왑",
swap_iq_to_eos: "IQ를 EOS로 스왑",
transactions_broadcasted: "브로드캐스트된 트랜잭션",
loadingVotes: "투표 로딩중"

**Comment by kesar** [comment]
cz

voting: "投票"
close_details: "关闭详情"
open_details: "打开详情"
started: "开始"
at: "时间"
ending: "结束中"
ended: "已结束"
select_for_voting: "选择投票"
selected: "已选"
see_on_snapshot: "前往提案",
details: "详情"
votes_breakdown: "投票明细"
from: "从"
tx_executed: "Tx 已执行"
voting: "投票中"
select_a_proposal: "选择一个提案"
select_proposal_to_see_details: "选择一个提案以了解详情"
vote: "投票"
voting_ended: "投票结束"
no_votes_so_far: "暂无投票"
swap_to_iq_erc20: "交易IQ至ERC20"
swap_iq_to_eos: "交易IQ至EOS"
transactions_broadcasted: "交易已广播"
loadingVotes: "加载投票"

**Comment by JustinCast** [comment]
@kesar we need some more entries:
## ko
- holders: "Holders",
- volume: "volume",
- total: "total",
- apps: "apps",
- prediqt_markets: "PredIQt markets",
- everipedia_articles: "Everipedia articles",
- everipedia_onchain_edits: "Everipedia Onchain Edits",
- everipedia_page_views: "Everipedia Page Views",
- liquidity: "liquidity",
- social: "Social",
- twitter_follower: "Twitter followers"

## cz
- holders: "Holders",
- volume: "volume",
- total: "total",
- apps: "apps",
- prediqt_markets: "PredIQt markets",
- everipedia_articles: "Everipedia articles",
- everipedia_onchain_edits: "Everipedia Onchain Edits",
- everipedia_page_views: "Everipedia Page Views",
- liquidity: "liquidity",
- social: "Social",
- twitter_follower: "Twitter followers",
- login_info_eth: "Login on ETH Wallet to swap your tokens",
